# Generated by Django 2.2.5 on 2019-11-16 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Djan', '0003_student_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incomeid', models.IntegerField()),
                ('source', models.CharField(max_length=30)),
                ('date', models.DateField()),
            ],
        ),
    ]
