# Generated by Django 2.2.5 on 2019-11-17 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Djan', '0004_income'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expenditure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exid', models.IntegerField()),
                ('source', models.CharField(max_length=30)),
                ('date', models.DateField()),
            ],
        ),
    ]
