# Generated by Django 2.2.5 on 2019-11-25 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Djan', '0005_expenditure'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='amount',
            field=models.IntegerField(default='300'),
        ),
    ]
